  export const icon_map: Record<string, string> = {
    'c#': 'csharp',
    'c++': 'cplusplus',
    'next.js': 'nextdotjs',
    'node.js': 'nodedotjs',
    'reactjs': 'react',
    'react': 'react',
    'scikit-learn': 'scikitlearn',
    'spring boot': 'springboot',
    'ruby on rails': 'rubyonrails',
    'rails': 'rubyonrails',
    'aws': 'amazonwebservices',
    'gcp': 'googlecloud',
    'postgresql': 'postgresql',
    'linux admin': 'linux',
    'qt': 'qt',
    'pyqt6': 'qt',
    'express': 'express',
    'go': 'go',
    'golang': 'go',
    'unity3d': 'unity',
    'kalilinux': 'kalilinux',
    'burp suite': 'burpsuite',
    'wireshark': 'wireshark'
  };