  export const simpleIcons: Record<string, string> = {
    'aws': 'amazonwebservices',
    'burp suite': 'burpsuite',
    'c#': 'csharp',
    'c++': 'cplusplus',
    'express': 'express',
    'gcp': 'googlecloud',
    'go': 'go',
    'golang': 'go',
    'kalilinux': 'kalilinux',
    'linux admin': 'linux',
    'next.js': 'nextdotjs',
    'node.js': 'nodedotjs',
    'postgresql': 'postgresql',
    'pyqt': 'qt',
    'pyqt6': 'qt',
    'qt': 'qt',
    'rails': 'rubyonrails',
    'react': 'react',
    'reactjs': 'react',
    'ruby on rails': 'rubyonrails',
    'scikit-learn': 'scikitlearn',
    'spring boot': 'springboot',
    'unity3d': 'unity',
    'wireshark': 'wireshark'
  };

export const devIcons: Record<string, string> = {
  "AWS": "amazonwebservices",
  "Azure": "azure",
  "Bash": "bash",
  "Batch": "windows11",
  "C#": "csharp",
  "Gitlab CI/CD": "gitlab",
  "Java": "java",
  "MATLAB": "matlab",
  "Matplotlib": "matplotlib",
  "PowerShell": "powershell",
  "Powershell": "powershell",
  "Tailwind CSS": "tailwindcss",
  "Tailwind": "tailwindcss",
  "TailwindCSS": "tailwindcss",
  "awk": "awk",
  "zsh": "zsh",
};

export const deviconSuffix: Record<string, string> = {
  "AWS": "-wordmark",
}

export const explicitIcons: Record<string, string> = {
  "Aircrack-ng": "https://www.kali.org/tools/aircrack-ng/images/aircrack-ng-logo.svg",
  "BeEF": "https://beefproject.com/images/logo.png",
  "Bloodhound": "https://mintcdn.com/specterops/NGsFbT_FAx51IRIW/logo/BHE-logo-square.svg?w=2500&fit=max&auto=format&n=NGsFbT_FAx51IRIW&q=85&s=02545df6c27dea3b50f461e2402b5725",
  "Bokeh": "https://static.bokeh.org/branding/icons/bokeh-icon.svg",
  "Fish": "https://fishshell.com/assets/img/Terminal_Logo_CRT_4.svg",
  "John the Ripper": "https://www.kali.org/tools/john/images/john-logo.svg",
  "LinPEAS": "https://www.kali.org/tools/peass-ng/images/peass-ng-logo.svg",
  "Maltego": "https://www.maltego.com/img/maltego-logo.svg",
  "Mathematica": "https://upload.wikimedia.org/wikipedia/commons/2/20/Mathematica_Logo.svg",
  "NLTK": "https://www.scnsoft.com/technologies-logos/large-language-models/nltk.svg",
  "Nmap": "https://nmap.org/images/sitelogo-2x.png",
  "OWASP ZAP": "https://www.zaproxy.org/img/zap-by-checkmarx.svg",
  "SQLMap": "https://www.kali.org/tools/sqlmap/images/sqlmap-logo.svg",
  "Seaborn": "https://seaborn.pydata.org/_images/logo-tall-lightbg.svg",
  "Shodan": "https://d34e3vwr98gw1q.cloudfront.net/a198b52fc288276a8f47dd819e3e56826fddae4af9fa230c9b2c6cfcbe5777b1/original/2641a8e2-fc8a-432e-b14f-2780b4d69f40.svg",
  "Sinatra": "https://img.site24x7static.com/images/sinatra.svg",
  "TOSCA": "https://cdn.brandfetch.io/idaXelRI63/theme/dark/symbol.svg?c=1bxid64Mup7aczewSAYMX&t=1668070825749",
  "Tricentis TOSCA": "https://cdn.brandfetch.io/idaXelRI63/theme/dark/symbol.svg?c=1bxid64Mup7aczewSAYMX&t=1668070825749",
  "XGBoost": "https://upload.wikimedia.org/wikipedia/commons/5/58/XGBoost_logo.svg",
  "hydra": "https://www.kali.org/tools/hydra/images/hydra-logo.svg",
}